Create a WebCocket layer
MusalaSoft/atmosphere-commons pull request #13
Opened 2017-05-09 15:31 UTC by dim4o

Add communicator manager and request/response message classes
Add utilities for data serialization/deserialization
Add data deserialization tests

2017-05-10 08:26 UTC, Perseverance requested changes

2017-05-10 08:26 UTC, Perseverance commented on src/main/java/com/musala/atmosphere/commons/websocket/WebSocketCommunicatorManager.java
> +    public ResponseMessage getServerResponse(String sessionId) {
Everything in this method can be written as just 
```java
return responseMap.remove(sessionId);
```
I would still keep it in two rows, for the sake of readability:
```java
ResponseMessage response = responseMap.remove(sessionId);
return response;
```

2017-05-10 08:26 UTC, Perseverance commented on src/main/java/com/musala/atmosphere/commons/websocket/message/Message.java
> +    public Message(String sessionId, MessageAction messageAction, RoutingAction routingAction) {
I'd put sessionId as last param. This way the constructors have the message Action first all the time.

2017-05-10 08:26 UTC, Perseverance commented on src/main/java/com/musala/atmosphere/commons/websocket/message/Message.java
> +     * Sets an agent identifier.
I'd add in this javadoc, when/why are you supposed to use this.

2017-05-10 08:26 UTC, Perseverance commented on src/main/java/com/musala/atmosphere/commons/websocket/message/RequestMessage.java
> +        typeNames = new String[arguments.length];
Please add a comment, why do you need these names. The class by itself has no logic around them.

2017-05-10 08:26 UTC, Perseverance commented on src/main/java/com/musala/atmosphere/commons/websocket/message/ResponseMessage.java
> +     * Gets the response data.
Wrong Javadoc - please write what this is and what it should be used for

2017-05-10 08:26 UTC, Perseverance commented on src/main/java/com/musala/atmosphere/commons/websocket/message/ResponseMessage.java
> +     * Sets an exception to the response.
This javadoc is not meaningful to me. Is this response now an exception itself or does the response now contain an exception?

2017-05-10 10:41 UTC, Perseverance requested changes

2017-05-10 10:41 UTC, Perseverance commented on src/main/java/com/musala/atmosphere/commons/websocket/util/GsonUtil.java
> +        return type;
You can return directly from the cases in the switch statement, instead of breaking and returning the type.

2017-05-10 10:41 UTC, Perseverance commented on src/main/java/com/musala/atmosphere/commons/websocket/util/GsonUtil.java
> +
Add Comment why is this happening

2017-05-10 10:41 UTC, Perseverance commented on src/main/java/com/musala/atmosphere/commons/websocket/util/UiElementSelectorDeserializer.java
> +        LOGGER.debug(String.format("attributeProjectionMap: %s", attributeProjectionMap));
We probably dont need these logs

2017-05-10 10:41 UTC, Perseverance commented on src/main/java/com/musala/atmosphere/commons/websocket/util/UiElementSelectorDeserializer.java
> +            String cssAttributeName = entry.getKey();
Do these two rows as one

2017-05-10 16:05 UTC, dim4o commented on src/main/java/com/musala/atmosphere/commons/websocket/WebSocketCommunicatorManager.java
> +    public ResponseMessage getServerResponse(String sessionId) {
done

2017-05-10 16:05 UTC, dim4o commented on src/main/java/com/musala/atmosphere/commons/websocket/message/Message.java
> +    public Message(String sessionId, MessageAction messageAction, RoutingAction routingAction) {
done

2017-05-10 16:10 UTC, dim4o commented on src/main/java/com/musala/atmosphere/commons/websocket/message/RequestMessage.java
> +        typeNames = new String[arguments.length];
done

2017-05-10 16:11 UTC, dim4o commented on src/main/java/com/musala/atmosphere/commons/websocket/message/ResponseMessage.java
> +     * Gets the response data.
done

2017-05-10 16:23 UTC, dim4o commented on src/main/java/com/musala/atmosphere/commons/websocket/util/UiElementSelectorDeserializer.java
> +        LOGGER.debug(String.format("attributeProjectionMap: %s", attributeProjectionMap));
Later I'll change the log level globally from the log4j.properties file but I find it very useful for now

2017-05-10 16:25 UTC, dim4o commented on src/main/java/com/musala/atmosphere/commons/websocket/util/UiElementSelectorDeserializer.java
> +            String cssAttributeName = entry.getKey();
done

2017-05-10 16:41 UTC, dim4o commented on src/main/java/com/musala/atmosphere/commons/websocket/util/GsonUtil.java
> +
done

2017-05-10 16:48 UTC, dim4o commented on src/main/java/com/musala/atmosphere/commons/websocket/util/GsonUtil.java
> +        return type;
I find using the return statement once in a method less confusing than using it in several places.

2017-05-12 12:58 UTC, dim4o commented on src/main/java/com/musala/atmosphere/commons/websocket/message/ResponseMessage.java
> +     * Sets an exception to the response.
done

2017-05-12 13:25 UTC, Perseverance approved these changes

2017-05-22 15:29 UTC, bstrandjev requested changes

2017-05-22 15:29 UTC, bstrandjev commented on src/test/java/com/musala/atmosphere/websocket/util/BaseDataSerialization.java
> +public class BaseDataSerialization {
BaseDataSerialization -> DataSerializationTestBase

2017-05-22 15:29 UTC, bstrandjev commented on src/test/java/com/musala/atmosphere/websocket/util/CollectionsDeserialziationTest.java
> +        AccessibilityElement seconfElement = new AccessibilityElement();
seconf - >second

2017-05-22 15:29 UTC, bstrandjev commented on src/test/java/com/musala/atmosphere/websocket/util/CollectionsDeserialziationTest.java
> +        Assert.assertEquals("first_value", (deserializedResponseData.get(0).get("first")));
Doesn't the ordinary equals of map suffice?

2017-05-22 15:29 UTC, bstrandjev commented on src/test/java/com/musala/atmosphere/websocket/util/CollectionsDeserialziationTest.java
> +        Assert.assertEquals(2, deserializedResponseData.size());
Doesn't the ordinary equals of list suffice?

2017-05-22 15:29 UTC, bstrandjev commented on src/test/java/com/musala/atmosphere/websocket/util/CollectionsDeserialziationTest.java
> +        Assert.assertEquals(3, deserializedResponseData.size());
Doesn't the ordinary equals of set suffice?

2017-05-22 15:29 UTC, bstrandjev commented on src/test/java/com/musala/atmosphere/websocket/util/CollectionsDeserialziationTest.java
> +        Assert.assertEquals(list, ((List<Pair<String, String>>)expected.getData()));
maybe assert on the action too?

2017-05-22 15:29 UTC, bstrandjev commented on src/test/java/com/musala/atmosphere/websocket/util/CustomDataDeserializationTest.java
> +        Assert.assertEquals(new Pair<Integer, Integer>(TestConst.RESOLUTION_X, TestConst.RESOLUTION_Y),
Either this line or the two above are not needed.

2017-05-22 15:29 UTC, bstrandjev commented on src/test/java/com/musala/atmosphere/websocket/util/CustomDataDeserializationTest.java
> +        Node<AccessibilityElement> childOfsecondChildNode = new Node<AccessibilityElement>(childOfFirstChildElement);
here the name does not match the actual purpose
Furthermore, please capitalise Second

2017-05-22 15:29 UTC, bstrandjev commented on src/test/java/com/musala/atmosphere/websocket/util/CustomDataDeserializationTest.java
> +        Object[] argsuments = message.getArguments();
argsuments -> arguments

2017-05-22 15:29 UTC, bstrandjev commented on src/test/java/com/musala/atmosphere/websocket/util/ExceptionDataDeserializationTest.java
> +    public void throwDeserializedExcpetionTest() throws Exception {
Excpetion -> Exception

2017-05-22 15:29 UTC, bstrandjev commented on src/test/java/com/musala/atmosphere/websocket/util/ExceptionDataDeserializationTest.java
> +        AtmosphereConfigurationException expectedExcpetion = new AtmosphereConfigurationException(EXCEPTION_MESSAGE);
expectedExcpetion -> expectedException

2017-05-22 15:29 UTC, bstrandjev commented on src/test/java/com/musala/atmosphere/websocket/util/ExceptionDataDeserializationTest.java
> +        throw actualException;
why do you throw if you have already verified the exception class?

2017-05-22 15:29 UTC, bstrandjev commented on src/test/java/com/musala/atmosphere/websocket/util/ExceptionDataDeserializationTest.java
> +    }
why do you throw if you have already verified the exception class?

2017-05-22 15:29 UTC, bstrandjev commented on src/test/java/com/musala/atmosphere/websocket/util/IntentDataDeserializationTest.java
> +        Assert.assertEquals(expectedFlags, actualFlags);
lines 45 and 46 make lines 39-42 useless

2017-05-22 15:29 UTC, bstrandjev commented on src/test/java/com/musala/atmosphere/websocket/util/IntentDataDeserializationTest.java
> +        Assert.assertEquals(0, intent.getCategory().size());
why a method returning a list is names in singular?

2017-05-22 15:29 UTC, bstrandjev commented on src/test/java/com/musala/atmosphere/websocket/util/IntentDataDeserializationTest.java
> +        Assert.assertTrue(person.equals(packObj.getSerializable("person")));
use assertEquals

2017-05-22 15:29 UTC, bstrandjev commented on src/test/java/com/musala/atmosphere/websocket/util/SimpleDataDeserializationTest.java
> +        Assert.assertEquals(8, deserializedResponseData.length);
this is checked below

2017-05-22 15:29 UTC, bstrandjev commented on src/test/java/com/musala/atmosphere/websocket/util/UiElementSelectorDeserializationTest.java
> +        Assert.assertEquals(uiElementSelector.getClassName(), "android.widget.NumberPicker");
hmm shouldn't the class be com.musala.atmosphere.commons.ui.selector.UiElementSelector

2017-05-22 15:29 UTC, bstrandjev commented on src/test/java/com/musala/atmosphere/websocket/util/UiElementSelectorDeserializationTest.java
> +        Assert.assertEquals(uiElementSelector.getStringValueWithSelectionOption(CssAttribute.CLASS_NAME)
isn't that index?

2017-05-23 09:10 UTC, bstrandjev requested changes

2017-05-23 09:10 UTC, bstrandjev commented on src/main/java/com/musala/atmosphere/commons/websocket/util/GsonUtil.java
> +                                                                     new ResponseMessageSeriazlizer())
Seriazlizer - > Serializer

2017-05-23 09:10 UTC, bstrandjev commented on src/main/java/com/musala/atmosphere/commons/websocket/util/GsonUtil.java
> +                                       .registerTypeHierarchyAdapter(Pack.class, new PackDeserializer())
better split the builder invocations in separate lines with ; at the end

2017-05-23 09:10 UTC, bstrandjev commented on src/main/java/com/musala/atmosphere/commons/websocket/util/GsonUtil.java
> +    public Object getProperty(String jsonMessage, String propertyName, Class<?> clazz) {
Btw here you can spare the need of casting:
```
 public <T> T getProperty(String jsonMessage, String propertyName, Class<T> clazz) {
         JsonObject jsonObject = g.fromJson(jsonMessage, JsonObject.class);
         JsonElement propertyElement = jsonObject.get(propertyName);
         T propertyData = g.fromJson(propertyElement, clazz);
 
         return propertyData;
     }
```

2017-05-23 09:10 UTC, bstrandjev commented on src/main/java/com/musala/atmosphere/commons/websocket/util/JsonConst.java
> +public class JsonConst {
Better declare as interface. Then you can spare quite a bit of the attribute accessors

2017-05-23 09:10 UTC, bstrandjev commented on src/main/java/com/musala/atmosphere/commons/websocket/util/deserializer/ResponseMessageDeserializer.java
> +        return jsonResponse.get(property) != null ? jsonResponse.get(property).getAsString() : null;
I like this approach better - you could have implemented it in RequestMessageDeserializer too
However, please introduce intermediate variable for jsonResponse.get(property) - otherwise you perform the json traversal twice

2017-05-23 09:10 UTC, bstrandjev commented on src/main/java/com/musala/atmosphere/commons/websocket/util/deserializer/UiElementSelectorDeserializer.java
> +        if (attributeProjectionMap.equals(new JsonObject())) {
Hmm can it ever happen that jsonelement equals empty jsonobject?

2017-05-23 14:32 UTC, dim4o commented on src/test/java/com/musala/atmosphere/websocket/util/BaseDataSerialization.java
> +public class BaseDataSerialization {
done

2017-05-23 14:34 UTC, dim4o commented on src/test/java/com/musala/atmosphere/websocket/util/CollectionsDeserialziationTest.java
> +        Assert.assertEquals(2, deserializedResponseData.size());
Yes, of course. Done.

2017-05-23 14:34 UTC, dim4o commented on src/test/java/com/musala/atmosphere/websocket/util/CollectionsDeserialziationTest.java
> +        Assert.assertEquals(3, deserializedResponseData.size());
Done.

2017-05-23 14:35 UTC, dim4o commented on src/test/java/com/musala/atmosphere/websocket/util/CollectionsDeserialziationTest.java
> +        AccessibilityElement seconfElement = new AccessibilityElement();
Done.

2017-05-23 14:36 UTC, dim4o commented on src/test/java/com/musala/atmosphere/websocket/util/CollectionsDeserialziationTest.java
> +        Assert.assertEquals("first_value", (deserializedResponseData.get(0).get("first")));
Done.

2017-05-23 14:37 UTC, dim4o commented on src/test/java/com/musala/atmosphere/websocket/util/CollectionsDeserialziationTest.java
> +        Assert.assertEquals(list, ((List<Pair<String, String>>)expected.getData()));
Done.

2017-05-23 14:37 UTC, dim4o commented on src/test/java/com/musala/atmosphere/websocket/util/CustomDataDeserializationTest.java
> +        Assert.assertEquals(new Pair<Integer, Integer>(TestConst.RESOLUTION_X, TestConst.RESOLUTION_Y),
Done.

2017-05-23 14:37 UTC, dim4o commented on src/test/java/com/musala/atmosphere/websocket/util/CustomDataDeserializationTest.java
> +        Object[] argsuments = message.getArguments();
Done.

2017-05-23 14:38 UTC, dim4o commented on src/test/java/com/musala/atmosphere/websocket/util/ExceptionDataDeserializationTest.java
> +    public void throwDeserializedExcpetionTest() throws Exception {
Done.

2017-05-23 14:38 UTC, dim4o commented on src/test/java/com/musala/atmosphere/websocket/util/ExceptionDataDeserializationTest.java
> +        AtmosphereConfigurationException expectedExcpetion = new AtmosphereConfigurationException(EXCEPTION_MESSAGE);
Done.

2017-05-23 14:39 UTC, dim4o commented on src/test/java/com/musala/atmosphere/websocket/util/IntentDataDeserializationTest.java
> +        Assert.assertEquals(0, intent.getCategory().size());
Done.

2017-05-23 14:39 UTC, dim4o commented on src/test/java/com/musala/atmosphere/websocket/util/SimpleDataDeserializationTest.java
> +        Assert.assertEquals(8, deserializedResponseData.length);
Done.

2017-05-23 14:42 UTC, dim4o commented on src/test/java/com/musala/atmosphere/websocket/util/UiElementSelectorDeserializationTest.java
> +        Assert.assertEquals(uiElementSelector.getClassName(), "android.widget.NumberPicker");
No. This is the name of the CLASS_NAME attribute, not the name of the uiElementSelector class.

2017-05-23 14:43 UTC, dim4o commented on src/main/java/com/musala/atmosphere/commons/websocket/util/GsonUtil.java
> +                                       .registerTypeHierarchyAdapter(Pack.class, new PackDeserializer())
Done.

2017-05-23 14:43 UTC, dim4o commented on src/main/java/com/musala/atmosphere/commons/websocket/util/GsonUtil.java
> +                                                                     new ResponseMessageSeriazlizer())
Done.

2017-05-23 14:46 UTC, dim4o commented on src/main/java/com/musala/atmosphere/commons/websocket/util/GsonUtil.java
> +    public Object getProperty(String jsonMessage, String propertyName, Class<?> clazz) {
Thanks. An excellent solution!

2017-05-23 14:46 UTC, dim4o commented on src/main/java/com/musala/atmosphere/commons/websocket/util/JsonConst.java
> +public class JsonConst {
Done.

2017-05-23 14:46 UTC, dim4o commented on src/main/java/com/musala/atmosphere/commons/websocket/util/deserializer/ResponseMessageDeserializer.java
> +        return jsonResponse.get(property) != null ? jsonResponse.get(property).getAsString() : null;
Done.

2017-05-23 14:52 UTC, dim4o commented on src/main/java/com/musala/atmosphere/commons/websocket/util/deserializer/UiElementSelectorDeserializer.java
> +        if (attributeProjectionMap.equals(new JsonObject())) {
Yes. See [responseWithEmptyArgumentDeserializationTest](https://github.com/MusalaSoft/atmosphere-commons/blob/websocket-agent-server/src/test/java/com/musala/atmosphere/websocket/util/CustomDataDeserializationTest.java#L137)

2017-05-23 16:17 UTC, bstrandjev requested changes

2017-05-23 16:17 UTC, bstrandjev commented on src/main/java/com/musala/atmosphere/commons/websocket/WebSocketCommunicatorManager.java
> +    private static Map<String, Object> lockObjectMap;
if you are doing singleton, you do not need its fields to be static

2017-05-23 16:17 UTC, bstrandjev commented on src/main/java/com/musala/atmosphere/commons/websocket/WebSocketCommunicatorManager.java
> +        if (instance == null) {
Double checked locking?

http://www.javaworld.com/article/2074979/java-concurrency/double-checked-locking--clever--but-broken.html

2017-05-23 16:17 UTC, bstrandjev commented on src/main/java/com/musala/atmosphere/commons/websocket/WebSocketCommunicatorManager.java
> +    public ResponseMessage getResponse(String sessionId) {
Get methods are not meant to be modifier. Rename to something more meaningful (like popResponse())

2017-05-23 16:17 UTC, bstrandjev commented on src/main/java/com/musala/atmosphere/commons/websocket/WebSocketCommunicatorManager.java
> +    public void setResponse(ResponseMessage response) {
addresponse

2017-05-25 11:39 UTC, dim4o commented on src/main/java/com/musala/atmosphere/commons/websocket/WebSocketCommunicatorManager.java
> +    public void setResponse(ResponseMessage response) {
Done.

2017-05-25 11:39 UTC, dim4o commented on src/main/java/com/musala/atmosphere/commons/websocket/WebSocketCommunicatorManager.java
> +    public ResponseMessage getResponse(String sessionId) {
Done.

2017-05-25 11:40 UTC, dim4o commented on src/main/java/com/musala/atmosphere/commons/websocket/WebSocketCommunicatorManager.java
> +    private static Map<String, Object> lockObjectMap;
Done.

2017-05-25 11:40 UTC, dim4o commented on src/main/java/com/musala/atmosphere/commons/websocket/WebSocketCommunicatorManager.java
> +        if (instance == null) {
Changed.

2017-07-25 13:45 UTC, merged